[package]
name = "sp1-guest"
version = "0.1.0"
edition = "2021"

[dependencies]
sp1-zkvm = "4.0.0"
leansig-core = { path = "../../core", features = ["sp1"] }
leansig-shared = { path = "../../shared" }